# Generated by Django 3.2.1 on 2021-05-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='on_sale',
        ),
    ]
