# Generated by Django 3.2.1 on 2021-05-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='category',
        ),
        migrations.DeleteModel(
            name='CerealImage',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='ClothesCategory',
        ),
    ]
