# Generated by Django 3.2.1 on 2021-05-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cereal',
            name='description',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='cereal',
            name='name',
            field=models.CharField(max_length=999),
        ),
    ]
