# Generated by Django 3.2.1 on 2021-05-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0002_auto_20210514_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cereal',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
