# Generated by Django 3.2.1 on 2021-05-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='on_sale',
        ),
    ]
