# Generated by Django 3.2.1 on 2021-05-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_on_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartCategory',
        ),
        migrations.RemoveField(
            model_name='cartimage',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartImage',
        ),
    ]
