# Generated by Django 3.2.1 on 2021-05-14 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_cereal',
        ),
    ]
